fullnameOverride: pulseops-observability

grafana:
  enabled: true
  adminPassword: pulseops
  defaultDashboardsEnabled: true
  service:
    type: ClusterIP
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
    datasources:
      enabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    scrapeInterval: 15s
    evaluationInterval: 15s
    retention: 2d
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi

alertmanager:
  enabled: true

prometheusOperator:
  admissionWebhooks:
    enabled: false

kube-state-metrics:
  enabled: true

nodeExporter:
  enabled: true
